[mysqld]
datadir=C:/Users/renat/Documents/GitHub/Dessik/.local/mysql-test-data
port=33316
[client]
port=33316
plugin-dir=C:\Users\renat\Documents\GitHub\Dessik\.local\mariadb-11.4.11-winx64/lib/plugin
