from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
nav = '''<a class="skip" href="#main">Pular para o conteúdo</a>
<div class="topnote">Loja fictícia · Compras simuladas, sem cobrança</div>
<header class="navbar"><div class="nav-inner"><a class="brand" href="/loja.html" aria-label="Dessik início">dessik<span>.</span></a>
<nav aria-label="Navegação principal"><a href="/loja.html">Produtos</a><a href="/admin.html" data-admin hidden>Administração</a>
<a href="/login.html" data-guest>Entrar</a><a class="button secondary" href="/cadastro.html" data-guest>Criar conta</a>
<span class="nav-session" data-session hidden><span data-user></span><button class="secondary" data-logout>Sair</button></span></nav></div></header>'''
dialog = '''<dialog id="confirm-dialog" aria-labelledby="dialog-title"><h2 id="dialog-title"></h2><p></p><form method="dialog" class="actions"><button class="secondary" value="cancel" autofocus>Cancelar</button><button value="confirm">Confirmar</button></form></dialog>'''
notice = '<div id="message" class="message" role="status" aria-live="polite" hidden></div>'
pagination = '<div class="pagination"><button id="previous" class="secondary" disabled>Anterior</button><span id="page-number">Página 1</span><button id="next" class="secondary" disabled>Próxima</button></div>'

def page(filename, title, content, script):
    text = f'''<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Dessik: loja fictícia de tecnologia para um projeto acadêmico."><title>{title} | Dessik</title><link rel="icon" href="/images/placeholder.svg" type="image/svg+xml"><link rel="stylesheet" href="/css/style.css"><script type="module" src="/js/{script}.js"></script></head>
<body>{nav}<main id="main">{content}</main>{dialog}<footer><span><strong>dessik.</strong> Tecnologia para sua rotina.</span><span>Projeto acadêmico · Produtos e especificações fictícios</span></footer></body></html>
'''
    (root / 'public' / filename).write_text(text, encoding='utf-8')

shop = f'''<section class="intro"><div><p class="eyebrow">Seu próximo upgrade</p><h1>Um novo ritmo para<br>o seu setup.</h1><p>Encontre o essencial para estudar, trabalhar e jogar.</p></div><span class="pill">Explore. Escolha. Experimente.</span></section>{notice}
<section aria-labelledby="catalog-title"><div class="catalog-bar"><div><h2 id="catalog-title">Nossos produtos</h2><span id="product-count" class="muted">Carregando catálogo…</span></div><button id="reload" class="secondary">Atualizar</button></div><div id="products" class="grid" aria-busy="true"></div>{pagination}</section>'''
page('loja.html', 'Loja', shop, 'loja')
page('index.html', 'Loja', shop, 'loja')
page('login.html', 'Entrar', f'''<div class="form-layout"><section class="form-intro"><p class="eyebrow">Bom ter você de volta</p><h1>Seu setup começa<br>por aqui.</h1><p>Entre na sua conta para explorar os produtos e simular sua próxima compra.</p><a href="/loja.html">← Continuar explorando</a></section><section class="form-panel"><h2>Entrar na conta</h2>{notice}<form id="login-form"><div class="fields"><label>E-mail<input type="email" name="email" autocomplete="email" maxlength="254" required></label><label>Senha<input type="password" name="senha" autocomplete="current-password" maxlength="72" required></label></div><div class="actions"><button class="full" type="submit">Entrar</button></div></form><p class="form-foot">Ainda não tem conta? <a href="/cadastro.html">Cadastre-se</a></p></section></div>''', 'login')
page('cadastro.html', 'Criar conta', f'''<div class="form-layout"><section class="form-intro"><p class="eyebrow">Vamos começar</p><h1>Suas ideias.<br>Seu próximo setup.</h1><p>Crie sua conta para experimentar a loja. Todas as compras são simulações, sem pagamento.</p><a href="/loja.html">← Conhecer os produtos</a></section><section class="form-panel"><h2>Crie sua conta</h2>{notice}<form id="register-form"><div class="fields"><label>Nome<input name="nome" autocomplete="name" minlength="2" maxlength="100" required></label><label>E-mail<input type="email" name="email" autocomplete="email" maxlength="254" required></label><label>Senha<input type="password" name="senha" autocomplete="new-password" minlength="8" maxlength="72" aria-describedby="password-hint" required><span class="hint" id="password-hint">Pelo menos 8 caracteres. Use uma senha exclusiva.</span></label><button class="secondary" type="button" id="generate-password">Sugerir senha segura</button><label>Confirmar senha<input type="password" name="confirmar_senha" autocomplete="new-password" minlength="8" maxlength="72" required></label></div><div class="form-section"><h3>Endereço</h3><p class="hint">Opcional. Consulte o CEP ou preencha manualmente.</p></div><div class="fields"><label>CEP<input name="cep" autocomplete="postal-code" inputmode="numeric" pattern="[0-9]{{5}}-?[0-9]{{3}}" maxlength="9" placeholder="00000-000"></label><button type="button" class="secondary" id="lookup-cep">Consultar CEP</button><div class="message" id="cep-message" role="status" hidden></div><label>Logradouro<input name="logradouro" autocomplete="address-line1" maxlength="150"></label><label>Bairro<input name="bairro" maxlength="100"></label><div class="two-cols"><label>Cidade<input name="cidade" autocomplete="address-level2" maxlength="100"></label><label>Estado (UF)<input name="estado" autocomplete="address-level1" maxlength="2" pattern="[A-Za-z]{{2}}" placeholder="SP"></label></div></div><div class="actions"><button class="full" type="submit">Cadastrar</button></div></form><p class="form-foot">Já tem uma conta? <a href="/login.html">Entrar</a></p></section></div>''', 'cadastro')
page('admin.html', 'Administração', f'''<section class="intro"><div><p class="eyebrow">Administração</p><h1>Seu catálogo, em dia.</h1><p>Cadastre produtos, ajuste preços e acompanhe o estoque.</p></div></section>{notice}<div id="admin-content" class="admin-layout" hidden><section class="form-panel"><h2 id="form-title">Novo produto</h2><form id="product-form"><div class="fields"><label>Nome<input name="nome" minlength="2" maxlength="120" required></label><label>Descrição<textarea name="descricao" maxlength="2000" required></textarea></label><label>Categoria<input name="categoria" maxlength="60" required></label><div class="two-cols"><label>Preço (R$)<input name="preco" type="number" min="0.01" max="99999999.99" step="0.01" required></label><label>Estoque<input name="quantidade_estoque" type="number" min="0" max="1000000" step="1" required></label></div><label>Imagem<input name="imagem_url" value="/images/placeholder.svg" maxlength="1000" required><span class="hint">URL HTTPS ou caminho em /images/.</span></label></div><div class="actions"><button id="save-product" type="submit">Cadastrar produto</button><button id="cancel-edit" type="button" class="secondary">Limpar</button></div></form></section><section aria-label="Produtos cadastrados"><div class="table-wrap"><table><thead><tr><th scope="col">Produto</th><th scope="col">Preço</th><th scope="col">Estoque</th><th scope="col">Ações</th></tr></thead><tbody id="product-rows"></tbody></table></div>{pagination}</section></div>''', 'admin')

csp = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'"
config = {'$schema': 'https://openapi.vercel.sh/vercel.json', 'framework': 'fastapi',
          'functions': {'api/index.py': {'maxDuration': 30, 'excludeFiles': '{tests/**,docs/**,.local/**,.venv/**}'}},
          'headers': [{'source': '/(.*)', 'headers': [{'key': 'X-Content-Type-Options', 'value': 'nosniff'}, {'key': 'X-Frame-Options', 'value': 'DENY'}, {'key': 'Referrer-Policy', 'value': 'strict-origin-when-cross-origin'}]},
                      {'source': '/:page*.html', 'headers': [{'key': 'Content-Security-Policy', 'value': csp}]},
                      {'source': '/', 'headers': [{'key': 'Content-Security-Policy', 'value': csp}]},
                      {'source': '/api/(.*)', 'headers': [{'key': 'Cache-Control', 'value': 'no-store'}]}]}
(root / 'vercel.json').write_text(json.dumps(config, indent=2) + '\n', encoding='utf-8')
print('HTMLs completos e configuração Vercel criados.')
